name: Gradle Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Initialize caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/loom-cache
            ~/.gradle/wrapper
          key: ${{ runner.os }}-build-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: versions/*.jar

      - name: (1) Publish release
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: m5T5xmUy
          modrinth-featured: false
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 1026394
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-tag: ${{ inputs.version }}+1.20.6
          github-generate-changelog: false
          github-draft: false
          github-prerelease: false
          github-token: ${{ secrets.GITHUB_TOKEN }}

          files: |
            versions/*1.20.6.jar
            versions/*1.20.6-sources.jar

          name: FabricBetterGrass ${{ inputs.version }}+1.20.6
          version: ${{ inputs.version }}+1.20.6
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: |
            fabric
          game-versions: |
            [1.20,1.21)
          game-version-filter: releases
          dependencies: |
            fabric-api(required){modrinth:P7dR8mSH}{curseforge:306612}#(ignore:github)
            yacl(required){modrinth:1eAoo2KR}{curseforge:667299}#(ignore:github)

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail

      - name: (2) Publish release
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: m5T5xmUy
          modrinth-featured: false
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 1026394
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-tag: ${{ inputs.version }}+1.21rc1
          github-generate-changelog: false
          github-draft: false
          github-prerelease: false
          github-token: ${{ secrets.GITHUB_TOKEN }}

          files: |
            versions/*1.21rc1.jar
            versions/*1.21rc1-sources.jar

          name: FabricBetterGrass ${{ inputs.version }}+1.21rc1
          version: ${{ inputs.version }}+1.21rc1
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: |
            fabric
          game-versions: |
            >1.20.6
          game-version-filter: none
          dependencies: |
            fabric-api(required){modrinth:P7dR8mSH}{curseforge:306612}#(ignore:github)
            yacl(required){modrinth:1eAoo2KR}{curseforge:667299}#(ignore:github)

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail
