name: Gradle Build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        java: [ 21 ]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: bash ./gradlew build --stacktrace

      - uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
